- import_playbook: registervars.yaml hostset=realservers
- hosts: realservers
  serial: "{% if SERIAL_EXECUTION|int > 0 %}{{ SERIAL_EXECUTION|int }}{% else %}{{ SERIAL_EXECUTION_PB }}{% endif %}"
  roles:
    - copy-configuration-directory
  vars_files:
    - "vars/common-vars.yaml"
