- hosts: "{{ hostset }}"
  become: yes
  pre_tasks:
     - raw: apt update && apt-get -y install python3-pip && /usr/bin/python3 -m pip install docker && /usr/bin/python3 -m pip install -U pip setuptools && /usr/bin/python3 -m pip install docker-compose
  serial: "{% if SERIAL_EXECUTION|int > 0 %}{{ SERIAL_EXECUTION|int }}{% else %}{{ SERIAL_EXECUTION_PB }}{% endif %}"
  roles:
    - init
  vars_files:
    - "vars/common-vars.yaml"
