PRESET_BASE: minimal
CONFIG_NAME: minimal
TERMINAL_TOTAL_DIFFICULTY: '5'
TERMINAL_BLOCK_HASH: '0x0000000000000000000000000000000000000000000000000000000000000000'
TERMINAL_BLOCK_HASH_ACTIVATION_EPOCH: '0'
MIN_GENESIS_ACTIVE_VALIDATOR_COUNT: '40'
MIN_GENESIS_TIME: '1692374240'
GENESIS_FORK_VERSION: '0x00000001'
GENESIS_DELAY: '5'
ALTAIR_FORK_VERSION: '0x01000001'
ALTAIR_FORK_EPOCH: '10'
BELLATRIX_FORK_VERSION: '0x02000001'
BELLATRIX_FORK_EPOCH: '20'
CAPELLA_FORK_VERSION: '0x03000001'
CAPELLA_FORK_EPOCH: '18446744073709551615'
DENEB_FORK_VERSION: '0x04000001'
DENEB_FORK_EPOCH: '18446744073709551615'
SECONDS_PER_SLOT: '2'
SECONDS_PER_ETH1_BLOCK: '2'
MIN_VALIDATOR_WITHDRAWABILITY_DELAY: '256'
SHARD_COMMITTEE_PERIOD: '64'
ETH1_FOLLOW_DISTANCE: '1'
INACTIVITY_SCORE_BIAS: '4'
INACTIVITY_SCORE_RECOVERY_RATE: '16'
EJECTION_BALANCE: '16000000000'
MIN_PER_EPOCH_CHURN_LIMIT: '4'
CHURN_LIMIT_QUOTIENT: '32'
PROPOSER_SCORE_BOOST: '40'
DEPOSIT_CHAIN_ID: '10'
DEPOSIT_NETWORK_ID: '11111'
DEPOSIT_CONTRACT_ADDRESS: '0x4242424242424242424242424242424242424242'