- name: Check if operating system is Ubuntu
  fail: msg="Please use Ubuntu as operating system."
  when: ansible_distribution != 'Ubuntu'
- name: Restart Docker daemon
  systemd:
    state: restarted
    daemon_reload: yes
    name: docker
  become: true
- name: Build an Ubuntu image for solana
  docker_image:
    build:
      network: host
      path: "{{ DOCKERFILE_PATH }}/"
      nocache: "yes"
      pull: "yes"
    name: ubuntu-solana
    force: "{{ REBUILD_UBUNTU_SOLANA_DOCKERFILE }}"
    source: "build"
