- name: Get current user
  command: whoami
  register: current_user
  tags:
  - bm-set
  - chown
- name: Create configuration directory
  file:
    path: "{{ DIEM_CONFIGURATION_PATH_AND_DOCKER_COMPOSE_PATH }}/{{ item }}"
    state: directory
    owner: "{{ current_user.stdout }}"
    group: "{{ current_user.stdout }}"
  loop: "{{ groups['node'] }}"
  loop_control:
    index_var: my_idx
    loop_var: item
  tags:
  - bm-set

- name: "Check if numnodes-{{ NUMBER_OF_NODES_TOTAL }}-numprepareaccounts-{{ NUM_PREPARE_ACCOUNTS }}.diemaccs exists"
  stat:
    path: "/tmp/numnodes-{{ NUMBER_OF_NODES_TOTAL }}-numprepareaccounts-{{ NUM_PREPARE_ACCOUNTS }}.diemaccs"
  register: stat_result
  tags:
  - bm-set
- name: "Create numnodes-{{ NUMBER_OF_NODES_TOTAL }}-numprepareaccounts-{{ NUM_PREPARE_ACCOUNTS }}.diemaccs"
  file:
    path: "/tmp/numnodes-{{ NUMBER_OF_NODES_TOTAL }}-numprepareaccounts-{{ NUM_PREPARE_ACCOUNTS }}.diemaccs"
    state: touch
  when: not stat_result.stat.exists
  tags:
  - bm-set

- name: Create node configuration files
  template:
    src: "{{ MAIN_CONFIG_PATH }}/node-configuration.j2"
    dest: "{{ DIEM_CONFIGURATION_PATH_AND_DOCKER_COMPOSE_PATH }}/{{ item }}/diem-node-{{ my_idx }}.yaml"
    owner: "{{ current_user.stdout }}"
    group: "{{ current_user.stdout }}"
  loop: "{{ groups['node'] }}"
  loop_control:
    index_var: my_idx
    loop_var: item
  tags:
  - bm-set
- name: Create expect script
  template:
    src: "{{ MAIN_CONFIG_PATH }}/prepare-nodes.j2"
    dest: "{{ MAIN_CONFIG_PATH }}/prepare-nodes.expect"
  tags:
  - bm-set
- name: Prepare nodes
  shell: . ~/.cargo/env && expect {{ MAIN_CONFIG_PATH }}/prepare-nodes.expect
  register: expect_output
  when: not stat_result.stat.exists
  tags:
  - bm-set
- name: Debug output
  debug:
    msg: "{{ expect_output.stdout }}"
  when: not stat_result.stat.exists
  tags:
  - bm-set

- name: Register hostname
  command: hostname
  register: hostname
  tags:
  - bm-set
#- name: Delete directories for node configuration
#  file:
#    path: "{{ DIEM_CONFIGURATION_PATH_AND_DOCKER_COMPOSE_PATH }}/{{ item }}"
#    state: absent
#  loop: "{{ groups['node'] }}"
#  loop_control:
#    loop_var: item
#    index_var: my_idx
#- name: Create directories for node configuration
#  file:
#    path: "{{ DIEM_CONFIGURATION_PATH_AND_DOCKER_COMPOSE_PATH }}/{{ item }}"
#    state: directory
#    owner: "{{ current_user.stdout }}"
#    group: "{{ current_user.stdout }}"
#  loop: "{{ groups['node'] }}"
#  loop_control:
#    loop_var: item
#    index_var: my_idx
- name: Create telegraf.conf
  template:
    src: "{{ MAIN_CONFIG_PATH }}/telegraf-container.j2"
    dest: "{{ DIEM_CONFIGURATION_PATH_AND_DOCKER_COMPOSE_PATH }}/{{ item }}/diem-node-{{ my_idx }}_telegraf.conf"
  loop: "{{ groups['node'] }}"
  loop_control:
    loop_var: item
    index_var: my_idx
  tags:
  - bm-set
