- import_playbook: registervars.yaml hostset=ca
- hosts: ca
  serial: "{% if SERIAL_EXECUTION|int > 0 %}{{ SERIAL_EXECUTION|int }}{% else %}{{ SERIAL_EXECUTION_PB }}{% endif %}"
  roles:
    - ca
  vars_files:
    - "vars/common-vars.yaml"
