- import_playbook: registervars.yaml hostset=couchdb
- hosts: couchdb
  serial: "{% if SERIAL_EXECUTION|int > 0 %}{{ SERIAL_EXECUTION|int }}{% else %}{{ SERIAL_EXECUTION_PB }}{% endif %}"
  roles:
    - couchdb
  vars_files:
    - "vars/common-vars.yaml"
