- import_playbook: registervars.yaml hostset=kafka
- hosts: kafka
  serial: "{% if SERIAL_EXECUTION|int > 0 %}{{ SERIAL_EXECUTION|int }}{% else %}{{ SERIAL_EXECUTION_PB }}{% endif %}"
  roles:
    - kafka
  vars_files:
    - vars/common-vars.yaml
