- import_playbook: registervars.yaml hostset=zookeeper
- hosts: zookeeper
  serial: "{% if SERIAL_EXECUTION|int > 0 %}{{ SERIAL_EXECUTION|int }}{% else %}{{ SERIAL_EXECUTION_PB }}{% endif %}"
  roles:
    - zookeeper
  vars_files:
    - vars/common-vars.yaml
