{
 "title": "FullNodes",
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  { "title": "State Sync", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "State Sync Lag",
   "type": "graph",
   "description": "Ledger timestamp's lag compared to the nodes current time.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "(diem_state_sync_timestamp{type=\"real\"} - on (instance, job) diem_state_sync_timestamp{type=\"synced\"})"
    }
   ]
  },
  {
   "title": "State Sync Version",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "locale" }
   ],
   "targets": [
    {
     "expr": "diem_state_sync_version{type=\"committed\"}",
     "legendFormat": "committed"
    },
    {
     "expr": "diem_state_sync_version{type=\"synced\"}",
     "legendFormat": "synced"
    }
   ]
  },
  {
   "title": "State Sync Rate",
   "type": "graph",
   "description": "Rate at which the synced version is increasing",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short", "label": "/s" }
   ],
   "targets": [
    {
     "expr": "rate(diem_state_sync_version{type=\"synced\"}[5m])"
    }
   ]
  },
  {
   "title": "Synchronized",
   "type": "graph",
   "description": "1 = It's fully synchronized\n0 = It's NOT synchronized",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "(diem_state_sync_version{type=\"highest\"} - on(instance, job) diem_state_sync_version{type=\"committed\"}) < bool 15"
    }
   ]
  },
  {
   "title": "State Sync Epoch",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "diem_state_sync_epoch", "legendFormat": "epoch" }
   ]
  },
  {
   "title": "State Sync Upstream Peers",
   "type": "graph",
   "description": "Number of upstream peers that can provide up to date information about the ledger.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(diem_state_sync_active_upstream_peers) by (instance, job) "
    }
   ]
  },
  { "title": "Mempool", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 } },
  {
   "title": "Mempool Pending transactions",
   "type": "graph",
   "description": "Number of uncommitted but still valid (not expired nor discarded) transactions in the nodes Mempool.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "diem_core_mempool_index_size{index=\"system_ttl\"}"
    }
   ]
  },
  {
   "title": "Mempool Txn Commit Latency",
   "type": "graph",
   "description": "The time between Mempool receiving the transaction and time to be committed. Note: due to reliability mechanisms, this value can be lower than it really is.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "diem_core_mempool_txn_commit_latency_sum / diem_core_mempool_txn_commit_latency_count"
    }
   ]
  },
  { "title": "Networking", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 } },
  {
   "title": "Network Connections (Incoming)",
   "type": "graph",
   "description": "Number of Inbound Connections as measured by DiemNet",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 35 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "diem_connections{direction=\"inbound\",network_id=\"Public\"}",
     "legendFormat": "{{peer_id}}"
    }
   ]
  },
  {
   "title": "Network Connections (Outgoing)",
   "type": "graph",
   "description": "Number of  Outbound Network Connections as measured by DiemNet",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 35 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "diem_connections{direction=\"outbound\",network_id=\"Public\"}",
     "legendFormat": "{{peer_id}}"
    }
   ]
  },
  {
   "title": "Transmit Bandwidth",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 43 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "irate(container_network_transmit_bytes_total[5m])"
    },
    {
     "expr": "irate(container_network_transmit_bytes_total[5m])",
     "legendFormat": "total"
    }
   ]
  },
  {
   "title": "Receive Bandwidth",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 43 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "irate(container_network_receive_bytes_total[5m])"
    },
    {
     "expr": "irate(container_network_receive_bytes_total[5m])",
     "legendFormat": "total"
    }
   ]
  },
  { "title": "System", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 51 } },
  {
   "title": "Disk Usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 52 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    { "expr": "container_fs_usage_bytes" }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 52 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "container_memory_working_set_bytes{instance=\"cadvisor:8098\", id=\"/\"}"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 60 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(container_cpu_usage_seconds_total{instance=\"cadvisor:8098\", id=\"/\"}[5m])"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 60 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "time() - container_start_time_seconds{id=\"/docker\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  }
 ]
}