- import_playbook: registervars.yaml hostlist=realservers
- hosts: "{{ hostset }}"
  serial: "{{ SERIAL_EXECUTION }}"
  roles:
    - common
  vars_files:
    - "vars/common-vars.yaml"
    - "vars/portainer-vars.yaml"
